version: '3.8'

volumes:
  cats_pg_data:
  static:
  media:

services:
  db:
    container_name: cats_db
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - cats_pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: cats_backend
    image: yois4101/kittygram_backend:latest
    volumes:
      - static:/app/static
      - media:/app/media
    env_file: .env
    depends_on:
      - db
    restart: always
    command: >
      bash -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0:8008 kittygram_backend.wsgi"

  frontend:
    container_name: cats_frontend
    image: yois4101/kittygram_frontend:latest
    volumes:
      - static:/frontend_static
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
  
  nginx:
    container_name: cats_gateway
    image: yois4101/kittygram_gateway:latest
    volumes:
      - static:/etc/nginx/html/static
      - media:/etc/nginx/html/media
    ports:
      - 9000:80
    depends_on:
      - backend
    restart: always
